name: Sketchin
favicon: null
layout_spectrum: 0.7801801429595798
typography_spectrum: 0.45829611527733505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5357880594674498
  lightness: 0.5514975390397012
  saturation: 0.5525547887664288
  rhythmicContrast: 0.9351851670071483
purpose: []
