name: Sketchin
favicon: null
layout_spectrum: 0.7801801429595798
typography_spectrum: 0.45829611527733505
title: Sketchin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ceddf0'
    - '#02081e'
    - '#396588'
    - '#7d232f'
    - '#dc5b4c'
  brandStrength: 0.6875
  lightness: 0.5514975390397012
  saturation: 0.5525547887664288
  rhythmicContrast: 0.9351851670071483
purpose: []
